const TextureList = {
  billboard01: "texture/billboard01.png",
  blackroof: "texture/blackroof.png",
  brickwall01: "texture/brickwall01.png",
  brickwall02: "texture/brickwall02.png",
  "brickwork-texture": "texture/brickwork-texture.png",
  ceilinglights01: "texture/ceilinglights0.png",
  concrete: "texture/concrete.png",
  dealershipsign1: "texture/dealershipsign1.png",
  greycarpet01: "texture/greycarpet01.png",
  greycarpet: "texture/greycarpet.png",
  greyroof: "texture/greyroof.png",
  gunshopsign1: "texture/gunshopsign1.png",
  lightbrick: "texture/lightbrick.png",
  lightplaster2: "texture/lightplaster2.png",
  lightplaster: "texture/lightplaster.png",
  redbricks: "texture/redbricks.png",
  red: "texture/red.png",
  shingleroof0: "texture/shingleroof0.png",
  shitwood: "texture/shitwood.png",
  signtest2: "texture/signtest2.png",
  uglyfloor0: "texture/uglyfloor0.png",
  wallpaint01: "texture/wallpaint01.png",
  whitecarpet01: "texture/whitecarpet01.png",
  whiteconcretegrid: "texture/whiteconcretegrid.png",
  whiteconcrete: "texture/whiteconcrete.png",
  woodpanels0: "texture/woodpanels0.png"
};

export default TextureList;